seed: ${seed}
max_epochs: 200
learning_rate: 1.0e-3
weight_decay: 1.0e-4
gradient_clip_val: 0.5
deterministic: true

temperature:
  initial: 1.0
  final: 1.0 # disabled, 1.0e-2
  anneal_epochs: 150

entropy_regularization:
  lambda_max: 0.0 # disabled, 1.0e-2
  warmup_epochs: 50

early_stopping:
  patience: 20
  monitor: val_loss
  mode: min

distributed:
  accelerator: auto
  devices: auto
  strategy: auto

scheduler:
  name: cosine
  eta_min_factor: 0.01
